### ISSUE TITLE
Implement login feature

### ISSUE THREAD

**Issue by vaastav** [CPSC319-2017w1/coast.the-terminal#22]
This requires the following things:

1. Having a login html page. @anushka864  to make one.
2. Setting up the login form. @anushka864  and @Shrey369  are in charge of this.
3. Adding a callback from frontend to the server passing the login data as well as input validation. @mahtaia  and @Shrey369 to do this.
4. Implementing server callbacks for Maia to call, figuring out the response object and implementing the database query for authentication. @StephenVanSon  and I will do this.

The User table has already been created in the database although hasn't been populated yet.

**Comment by vaastav** [comment]
We have the backend figured out.

An actual call needs to be setup so that responses can be passed to the webapp correctly.
Login css needs to be completed.

**Comment by StephenVanSon** [comment]
Login feature has been fully implemented. Closing.
