### ISSUE TITLE
Create the relevant tables in the Database

### ISSUE THREAD

**Issue by vaastav** [CPSC319-2017w1/coast.the-terminal#9]
- We need to first decide what tables we will be storing and how they will be represented. Hence, this is dependent on the completion of the ER diagram.

**Comment by StephenVanSon** [comment]
Created User table in database.

**Comment by StephenVanSon** [comment]
All tables aside from time and material needs (are we creating a table for this?) have been created.

**Comment by StephenVanSon** [comment]
Time and material needs column to be added to EngagementContract table.  Closing issue.
